import { createStyles } from "@mantine/core";

export const useBlobStyles = createStyles((theme) => ({
	file: {
		marginTop: "16px",
		position: "relative",
		backgroundColor: "var(--background-color)",
		border: "1px solid var(--border-hover-color)",
		borderRadius: "6px",
		boxSizing: "border-box",
		marginBottom: "16px",
		maxWidth: "100%",
	},
	fileHeader: {
		display: "flex",
		alignItems: "center",
		padding: "8px 16px",
		backgroundColor: "var(--background-hover-color)",
		borderBottom: "1px solid var(--border-hover-color)",
		borderTopLeftRadius: "6px",
		borderTopRightRadius: "6px",
		boxSizing: "border-box",
		height: "46px",
	},
	info: { fontSize: "14px", flex: 1 },
	divider: {
		display: "inline-block",
		width: "1px",
		height: "18px",
		marginRight: "4px",
		marginLeft: "4px",
		verticalAlign: "middle",
		borderLeft: "1px solid var(--border-hover-color)",
		margin: "0 16px",
	},
	icons: { display: "flex", alignItems: "center" },
	icon: { margin: "0 8px", cursor: "pointer", "&:hover svg:not(#copied)": { fill: "var(--link-color)" } },
	fileContent: {
		borderBottomLeftRadius: "6px",
		borderBottomRightRadius: "6px",
		padding: 0,
		userSelect: "text",
		overflowX: "auto",
	},
	markdownPadding: { padding: "40px" },
	fileInfo: {
		borderBottomLeftRadius: "6px",
		borderBottomRightRadius: "6px",
		padding: "16px",
		fontSize: "14px",
		color: "#c9d1d9",
	},
}));
