import { createStyles } from "@mantine/core";

export const useListStyles = createStyles((theme) => ({
	control: {},
	file: {
		marginTop: "16px",
		position: "relative",
		backgroundColor: "var(--background-color)",
		border: "1px solid var(--border-hover-color)",
		borderRadius: "6px",
		boxSizing: "border-box",
		marginBottom: "16px",
	},
	fileHeader: {
		display: "flex",
		alignItems: "center",
		padding: "8px 16px",
		backgroundColor: "var(--background-hover-color)",
		borderBottom: "1px solid var(--border-hover-color)",
		borderTopLeftRadius: "6px",
		borderTopRightRadius: "6px",
		boxSizing: "border-box",
		height: "46px",
	},
	info: { fontSize: "14px", flex: 1 },
	divider: {
		display: "inline-block",
		width: "1px",
		height: "18px",
		marginRight: "4px",
		marginLeft: "4px",
		verticalAlign: "middle",
		borderLeft: "1px solid var(--border-hover-color)",
		margin: "0 16px",
	},
	icons: { display: "flex", alignItems: "center" },
	icon: { margin: "0 8px", cursor: "pointer", "&:hover svg:not(#copied)": { fill: "var(--link-color)" } },
	fileContent: { borderBottomLeftRadius: "6px", borderBottomRightRadius: "6px", padding: 0, userSelect: "text" },
	markdownPadding: { padding: "40px" },
	fileNav: { display: "flex", alignItems: "start", marginBottom: "16px" },
	box: { marginBottom: "16px", backgroundColor: "var(--background-color)", border: "1px solid var(--border-hover-color)", borderRadius: "6px" },
	boxHeader: {
		position: "relative",
		margin: "-1px -1px 0",
		backgroundColor: "var(--background-hover-color)",
		border: "1px solid var(--border-hover-color)",
		borderTopLeftRadius: "6px",
		borderTopRightRadius: "6px",
		padding: "16px",
	},
	headerDetails: { display: "flex", alignItems: "center" },
	avatar: { backgroundColor: "transparent !important", borderRadius: "9999px" },
	moreDetails: { display: "flex", alignItems: "center", marginLeft: "16px", fontWeight: "bold", flex: 1 },
	commits: {
		color: "var(--text-color)",
		fontSize: "14px",
		display: "flex",
		alignItems: "center",
		"& > svg": { marginRight: "4px" },
	},
	fileInfo: {
		borderBottomLeftRadius: "6px",
		borderBottomRightRadius: "6px",
		padding: "16px",
		fontSize: "14px",
		color: "#c9d1d9",
	},
	markdown: { border: "1px solid var(--border-hover-color)", borderRadius: "6px", backgroundColor: "var(--background-color)" },
	markdownHeader: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		padding: "16px",
		fontSze: "14px",
		height: "54px",
		borderTopLeftRadius: "6px",
		borderTopRightRadius: "6px",
	},
	markdownTitle: { flex: 1, fontWeight: "bold" },
	markdownEdit: { cursor: "pointer", "&:hover svg": { fill: "var(--link-color)" } },
	markdownContent: { padding: "16px 32px 32px", borderBottomLeftRadius: "6px", borderBottomRightRadius: "6px" },
}));
