import { createStyles } from "@mantine/core";

export default createStyles(() => ({
	control: {
		backgroundColor: "var(--background-color)",
		padding: "16px 0 0",
		color: "#c9d1d9",
		width: "100%",
	},
	top: {
		margin: "0 0 16px",
		padding: "0 32px",
		display: "flex",
		height: "32px",
		alignItems: "center",
	},
	topLeft: {
		flex: 1,
		flexWrap: "nowrap",
		display: "flex",
		alignItems: "center",
		height: "30px",
		overflowX: "hidden",
		overflowY: "hidden",
	},
	topRight: { display: "flex", alignItems: "center", height: "30px" },
	icon: { marginRight: "8px", display: "flex", alignItems: "center", flexWrap: "nowrap" },
	anchor: {
		color: "var(--link-color) !important",
		fontSize: "20px !important",
		textDecoration: "none",
	},
	bottom: {
		padding: "0 32px",
		display: "flex",
		height: "48px",
		alignItems: "center",
		borderBottom: "1px solid rgba(240, 246, 252, .1)",
	},
	ul: {
		display: "flex",
		gap: "8px",
		alignItems: "center",
		listStyle: "none",
		margin: 0,
		padding: 0,
	},
	li: {
		position: "relative",
		height: "30px",
		display: "flex",
		alignItems: "center",
		padding: "0 8px",
		fontSize: "14px",
		whiteSpace: "nowrap",
		lineHeight: "38px",
		outlineOffset: "-8px",
		textAlign: "center",
		cursor: "pointer",
		backgroundColor: "transparent",
		border: 0,
		borderRadius: "6px",
		"&:before": {
			position: "absolute",
			top: "50%",
			left: "50%",
			width: "100%",
			height: "100%",
			minHeight: "48px",
			content: '""',
			transform: "translateX(-50%) translateY(-50%)",
		},
		boxSizing: "border-box",
		"&:hover": {
			backgroundColor: "rgba(177, 186, 196, .12)",
			transition: "background .12s ease-out",
		},
	},
	selected: {
		"&:before": {
			borderBottom: "2px solid var(--border-selected)",
			outlineOffset: "8px",
			boxSizing: "border-box",
		},
		fontWeight: "bold",
	},
	a: {
		textDecoration: "none",
		"&:visited": { textDecoration: "none", color: "var(--text-color)" },
		display: "flex",
		alignItems: "center",
		color: "var(--text-color)",
	},
}));
