name: Lint

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  Lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
